spring:
  application:
    name: ai-agent
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
# knife4j ??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.liucc.aiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
